version: '3.8'

services:
  localnativeprovider:
    image: localnativeprovider:latest
    container_name: localnativeprovider
    environment:
      - ConnectionStrings__Default=Server=172.17.0.2;Port=5432;Database=bikestores;User Id=postgres;Password=admin;
    ports:
      - "8080:8080"
    network_mode: bridge
    restart: always